require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")

-- plugins
require("plugins.autopairs")
require("plugins.cmp")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.lsp")
require("plugins.noice")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
